aistudio:
  base_url: "https://aistudio.baidu.com/llm/lmapi/v3"
  api_keys: ["", ""]

aistudio_app:
  base_url: "https://api-i0c6md2d80ndh773.aistudio-app.com/v1"
  api_keys: ["", ""]

dashscope:
  base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
  api_keys: ["", ""]

modelscope:
  base_url: "https://api-inference.modelscope.cn/v1/"
  api_keys: ["", ""]

zhipu:
  base_url: ""
  api_keys: ["", ""]
