# .github/workflows/release-simple.yml
# 简化版本的release workflow，作为主workflow的备选

name: Simple Release Workflow

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  simple-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -e .

      - name: Build package
        run: |
          pip install setuptools wheel
          python setup.py sdist bdist_wheel

      - name: Get commit history
        id: get_changelog
        run: |
          CURRENT_TAG=${{ github.ref_name }}
          PREVIOUS_TAG=$(git tag --sort=-v:refname | head -n 2 | tail -n 1)
          
          if [ -z "$PREVIOUS_TAG" ]; then
            COMMIT_LOG=$(git log --pretty=format:"- %s")
          else
            COMMIT_LOG=$(git log --pretty=format:"- %s" $PREVIOUS_TAG..$CURRENT_TAG)
          fi
          
          # 创建简单的release notes
          RELEASE_BODY="## What's Changed\n\n$COMMIT_LOG\n\n**Full Changelog**: https://github.com/${{ github.repository }}/compare/$PREVIOUS_TAG...$CURRENT_TAG"
          
          echo "release_body<<EOF" >> $GITHUB_OUTPUT
          echo "$RELEASE_BODY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          pip install twine
          twine upload dist/*

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.get_changelog.outputs.release_body }}
          files: dist/*